load("maxwellbase.mac");

assume(%chi>0);

ehclean_Asimp:blockmat(
  max_Asimp,
  hstack(
    vstack(epsinv*muinv*covect(n),zeromatrix(3,1)),
    vstack(zeromatrix(3,1),epsinv*muinv*covect(n))
  ),

  vstack(
    hstack(%chi^2*n,zeromatrix(1,3)),
    hstack(zeromatrix(1,3),%chi^2*n)
  ),
  zeromatrix(2,2)
);
ehclean_A:max_invsubst(ehclean_Asimp);
[ehclean_V, ehclean_D, ehclean_invV]:max_invsubst(hypdiagonalize(ehclean_Asimp));
