#! /usr/bin/python2.5

import pstats
import sys

p = pstats.Stats(sys.argv[1]).strip_dirs()
#p.sort_stats("time").print_stats(30)
#p.sort_stats("cumulative").print_stats(30)
p.sort_stats("time").print_callers()
